### ISSUE TITLE
Prototype Pollution in node-forge

### ISSUE THREAD

**Issue by coolandsmartrr** [forgojs/forgo-examples#3]
`parcel-bundler` is dependent on `node-forge@0.7.6`, which contains a vulnerability of [Prototype Pollution](https://www.npmjs.com/advisories/1561).[1] npmjs rates this as a high severity vulnerability.

[1] Checked via `npx npm-remote-ls parcel-bundler`

**Comment by jeswin** [comment]
I know, but it wouldn't affect us since 

- The package is private, so users aren't really affected
- parcel Is only working with known, safe inputs (ie, the code in this repo)

I'll update it as soon as a new release is available from parcel. Till then we can keep this open.

**Comment by coolandsmartrr** [comment]
Okay.

**Comment by jeswin** [comment]
They are unlikely to fix it. https://github.com/parcel-bundler/parcel/issues/5145
TBH, that's a bit surprising - since it scares off people.

So we moved from parcel to webpack across the project.
